import type { Metadata } from "next";
import "./globals.css";
import { twMerge } from 'tailwind-merge';
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import {DM_Sans} from 'next/font/google';
import  AppStateProvider  from "@/lib/providers/state-provider";


const inter = DM_Sans({subsets: ['latin']});

export const metadata: Metadata = {
  title: "Mindloom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={twMerge('bg-background', inter.className)}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <AppStateProvider>
           {children}
        </AppStateProvider>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
